// Package codexappserver drives Codex through `codex app-server` over stdio and
// normalizes its notifications into Kennel's provider-neutral Chat events.
//
// Transport: newline-delimited JSON. There is no "jsonrpc" version field — a
// frame is a request ({id, method, params}), a response ({id, result|error}), a
// notification ({method, params}), or a server->client request ({id, method,
// params}) that the client must answer or the turn stalls.
//
// The protocol surface is generated by `codex app-server generate-json-schema`,
// so the method names and payload shapes here are checked against that output
// rather than guessed.
package codexappserver

import (
	"bufio"
	"context"
	"crypto/sha256"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"sync"
	"sync/atomic"
	"time"
)

// frame is the union of every shape that crosses the wire.
type frame struct {
	ID     *json.RawMessage `json:"id,omitempty"`
	Method string           `json:"method,omitempty"`
	Params json.RawMessage  `json:"params,omitempty"`
	Result json.RawMessage  `json:"result,omitempty"`
	Error  *rpcError        `json:"error,omitempty"`
}

// rpcError is the error object on a failed response.
type rpcError struct {
	Code    int             `json:"code"`
	Message string          `json:"message"`
	Data    json.RawMessage `json:"data,omitempty"`
}

func (e *rpcError) Error() string {
	if e == nil {
		return ""
	}
	return fmt.Sprintf("app-server error %d: %s", e.Code, e.Message)
}

// notification is a server->client message with no id.
type notification struct {
	Method string
	Params json.RawMessage
}

// serverRequest is a server->client message that expects a reply. Approvals and
// user-input requests arrive this way, and the provider blocks on them.
type serverRequest struct {
	ID     json.RawMessage
	Method string
	Params json.RawMessage
}

// serverRequestHandler answers a server->client request. Returning an error
// sends a JSON-RPC error back, which the provider treats as a refusal to answer
// rather than as a decision.
type serverRequestHandler func(context.Context, serverRequest) (any, error)

// ErrConnClosed reports use of a connection whose process has exited.
var ErrConnClosed = errors.New("app-server connection closed")

// conn is one live stdio connection to an app-server process.
//
// It is transport only: framing, request/response correlation, and fan-out. It
// knows nothing about threads or turns, so it can be tested over an in-memory
// pipe with no child process.
type conn struct {
	w   io.WriteCloser
	log *slog.Logger

	nextID atomic.Int64

	// writeMu serializes writes. It is never held while waiting for a response.
	writeMu sync.Mutex
	// writeSequence is the actual order of complete client frames handed to the
	// transport. It is guarded by writeMu and is deliberately distinct from the
	// JSON-RPC request id: server replies and notifications also use this writer.
	writeSequence int64

	mu      sync.Mutex
	pending map[int64]chan frame
	closed  bool

	// notifications is bounded. Overflow is dropped and logged rather than
	// allowed to block the reader, which would deadlock the provider.
	notifications chan notification

	onServerRequest serverRequestHandler

	// done closes when the read loop exits, so a caller waiting on a response
	// learns the process died instead of blocking forever.
	done chan struct{}
	// readErr is set before done closes when the loop failed for a reason other
	// than clean EOF.
	readErr error
}

// transportReceipt proves only that one bounded client request frame was fully
// written. It intentionally carries no params, prompt text, raw bytes, thread
// identifiers, credentials, or provider response content.
type transportReceipt struct {
	RequestID       int64     `json:"request_id"`
	Method          string    `json:"method"`
	SHA256          string    `json:"sha256"`
	ByteCount       int       `json:"byte_count"`
	WriteSequence   int64     `json:"write_sequence"`
	SuccessfulWrite bool      `json:"successful_write"`
	WrittenAt       time.Time `json:"written_at"`
}

const notificationBuffer = 4096

func newConn(w io.WriteCloser, r io.Reader, log *slog.Logger, onReq serverRequestHandler) *conn {
	c := &conn{
		w:               w,
		log:             log,
		pending:         make(map[int64]chan frame),
		notifications:   make(chan notification, notificationBuffer),
		onServerRequest: onReq,
		done:            make(chan struct{}),
	}
	go c.readLoop(r)
	return c
}

// notifications the caller consumes. Closed when the connection ends.
func (c *conn) notifs() <-chan notification { return c.notifications }

// wait returns a channel closed when the connection ends.
func (c *conn) wait() <-chan struct{} { return c.done }

// err reports why the read loop stopped, or nil for a clean end.
func (c *conn) err() error {
	select {
	case <-c.done:
		return c.readErr
	default:
		return nil
	}
}

func (c *conn) readLoop(r io.Reader) {
	defer func() {
		c.mu.Lock()
		c.closed = true
		pending := c.pending
		c.pending = map[int64]chan frame{}
		c.mu.Unlock()

		// Unblock every in-flight request so no caller hangs on a dead process.
		for _, ch := range pending {
			close(ch)
		}
		close(c.notifications)
		close(c.done)
	}()

	br := bufio.NewReaderSize(r, 1<<20)
	for {
		line, err := readFrame(br)
		if err != nil {
			if !errors.Is(err, io.EOF) {
				c.readErr = err
			}
			return
		}
		if len(line) == 0 {
			continue
		}

		var f frame
		if err := json.Unmarshal(line, &f); err != nil {
			// One unparseable frame must not kill the connection: the provider
			// may add fields or emit something this build does not model.
			c.log.Warn("app-server frame not parseable", "error", err)
			continue
		}

		switch {
		case f.ID != nil && f.Method != "":
			go c.answer(serverRequest{ID: *f.ID, Method: f.Method, Params: f.Params})
		case f.ID != nil:
			c.deliver(f)
		case f.Method != "":
			select {
			case c.notifications <- notification{Method: f.Method, Params: f.Params}:
			default:
				c.log.Warn("dropped app-server notification: buffer full", "method", f.Method)
			}
		}
	}
}

// readFrame reads one newline-delimited frame with no length cap, so a large
// diff or command output cannot truncate the stream mid-JSON.
func readFrame(r *bufio.Reader) ([]byte, error) {
	var buf []byte
	for {
		chunk, err := r.ReadSlice('\n')
		buf = append(buf, chunk...)
		if errors.Is(err, bufio.ErrBufferFull) {
			continue
		}
		if err != nil {
			if len(buf) > 0 && errors.Is(err, io.EOF) {
				return trimEOL(buf), nil
			}
			return nil, err
		}
		return trimEOL(buf), nil
	}
}

func trimEOL(b []byte) []byte {
	for len(b) > 0 && (b[len(b)-1] == '\n' || b[len(b)-1] == '\r') {
		b = b[:len(b)-1]
	}
	return b
}

func (c *conn) deliver(f frame) {
	var id int64
	if err := json.Unmarshal(*f.ID, &id); err != nil {
		c.log.Warn("response with non-numeric id", "id", string(*f.ID))
		return
	}

	c.mu.Lock()
	ch, ok := c.pending[id]
	delete(c.pending, id)
	c.mu.Unlock()

	if !ok {
		// A response for a request we already gave up on. Expected after a
		// context timeout; not an error.
		c.log.Debug("response for unknown request id", "id", id)
		return
	}
	ch <- f
}

// answer runs the server-request handler and writes the reply. It runs on its
// own goroutine so a slow decision (a user staring at an approval card) does not
// stall the read loop and starve streaming deltas.
func (c *conn) answer(req serverRequest) {
	result, err := c.onServerRequest(context.Background(), req)

	reply := map[string]any{"id": req.ID}
	if err != nil {
		reply["error"] = rpcError{Code: -32000, Message: err.Error()}
	} else {
		reply["result"] = result
	}
	if werr := c.write(reply); werr != nil {
		c.log.Error("failed to answer app-server request", "method", req.Method, "error", werr)
	}
}

func (c *conn) write(v any) error {
	_, err := c.writeSerialized(v, 0, "", nil)
	return err
}

// writeSerialized is the only frame serialization/write boundary. For
// turn/start it validates the policy decoded from these exact serialized bytes
// before transport and returns a receipt only after the entire newline-delimited
// frame has been written successfully.
func (c *conn) writeSerialized(v any, requestID int64, method string, expectedSandboxPolicy map[string]any) (transportReceipt, error) {
	b, err := json.Marshal(v)
	if err != nil {
		return transportReceipt{}, fmt.Errorf("encode frame: %w", err)
	}
	b = append(b, '\n')
	if method == "turn/start" && expectedSandboxPolicy != nil {
		if err := validateSerializedTurnSandboxPolicy(b, expectedSandboxPolicy); err != nil {
			return transportReceipt{}, err
		}
	}

	c.writeMu.Lock()
	n, writeErr := c.w.Write(b)
	if writeErr != nil {
		c.writeMu.Unlock()
		return transportReceipt{}, fmt.Errorf("write frame: %w", writeErr)
	}
	if n != len(b) {
		c.writeMu.Unlock()
		return transportReceipt{}, fmt.Errorf("write frame: %w: wrote %d of %d bytes", io.ErrShortWrite, n, len(b))
	}
	c.writeSequence++
	sequence := c.writeSequence
	writtenAt := time.Now().UTC()
	c.writeMu.Unlock()

	if method == "" {
		return transportReceipt{}, nil
	}
	return transportReceipt{
		RequestID:       requestID,
		Method:          method,
		SHA256:          fmt.Sprintf("%x", sha256.Sum256(b)),
		ByteCount:       len(b),
		WriteSequence:   sequence,
		SuccessfulWrite: true,
		WrittenAt:       writtenAt,
	}, nil
}

func validateSerializedTurnSandboxPolicy(frameBytes []byte, expected map[string]any) error {
	if expected == nil {
		return errors.New("turn/start sandbox policy expectation is missing")
	}
	var sent struct {
		Method string `json:"method"`
		Params struct {
			SandboxPolicy json.RawMessage `json:"sandboxPolicy"`
		} `json:"params"`
	}
	if err := json.Unmarshal(frameBytes, &sent); err != nil {
		return fmt.Errorf("decode serialized turn/start frame: %w", err)
	}
	if sent.Method != "turn/start" {
		return fmt.Errorf("serialized turn/start method = %q", sent.Method)
	}
	if len(sent.Params.SandboxPolicy) == 0 {
		return errors.New("serialized turn/start sandbox policy is missing")
	}
	var got any
	if err := json.Unmarshal(sent.Params.SandboxPolicy, &got); err != nil {
		return fmt.Errorf("decode serialized turn/start sandbox policy: %w", err)
	}
	if !semanticJSONEqual(got, expected) {
		gotCanonical, _ := json.Marshal(got)
		wantCanonical, _ := json.Marshal(expected)
		return fmt.Errorf("serialized turn/start sandbox policy mismatch: got %s want %s", gotCanonical, wantCanonical)
	}
	return nil
}

func semanticJSONEqual(left, right any) bool {
	leftBytes, leftErr := json.Marshal(left)
	rightBytes, rightErr := json.Marshal(right)
	if leftErr != nil || rightErr != nil {
		return false
	}
	var leftValue, rightValue any
	if json.Unmarshal(leftBytes, &leftValue) != nil || json.Unmarshal(rightBytes, &rightValue) != nil {
		return false
	}
	leftCanonical, _ := json.Marshal(leftValue)
	rightCanonical, _ := json.Marshal(rightValue)
	return string(leftCanonical) == string(rightCanonical)
}

func canonicalRequestFrameDigest(requestID int64, method string, params any) (string, int, error) {
	payload := map[string]any{"id": requestID, "method": method}
	if params != nil {
		payload["params"] = params
	}
	b, err := json.Marshal(payload)
	if err != nil {
		return "", 0, err
	}
	b = append(b, '\n')
	return fmt.Sprintf("%x", sha256.Sum256(b)), len(b), nil
}

// request sends a client->server request and waits for its response. The caller's
// context bounds the wait; a late response is discarded by deliver.
func (c *conn) request(ctx context.Context, method string, params, out any) error {
	_, err := c.requestFrame(ctx, method, params, out, nil, false)
	return err
}

// requestWithTransportReceipt returns content-free evidence that the complete
// request frame crossed the transport through the same call that decodes the
// provider response.
func (c *conn) requestWithTransportReceipt(ctx context.Context, method string, params, out any, expectedSandboxPolicy map[string]any) (transportReceipt, error) {
	return c.requestFrame(ctx, method, params, out, expectedSandboxPolicy, true)
}

func (c *conn) requestFrame(ctx context.Context, method string, params, out any, expectedSandboxPolicy map[string]any, captureReceipt bool) (transportReceipt, error) {
	id := c.nextID.Add(1)
	ch := make(chan frame, 1)

	c.mu.Lock()
	if c.closed {
		c.mu.Unlock()
		return transportReceipt{}, fmt.Errorf("%s: %w", method, ErrConnClosed)
	}
	c.pending[id] = ch
	c.mu.Unlock()

	payload := map[string]any{"id": id, "method": method}
	if params != nil {
		payload["params"] = params
	}
	receiptMethod := ""
	if captureReceipt {
		receiptMethod = method
	}
	receipt, err := c.writeSerialized(payload, id, receiptMethod, expectedSandboxPolicy)
	if err != nil {
		c.mu.Lock()
		delete(c.pending, id)
		c.mu.Unlock()
		return transportReceipt{}, fmt.Errorf("%s: %w", method, err)
	}

	select {
	case <-ctx.Done():
		c.mu.Lock()
		delete(c.pending, id)
		c.mu.Unlock()
		return receipt, fmt.Errorf("%s: %w", method, ctx.Err())

	case f, ok := <-ch:
		if !ok {
			return receipt, fmt.Errorf("%s: %w", method, ErrConnClosed)
		}
		if f.Error != nil {
			return receipt, fmt.Errorf("%s: %w", method, f.Error)
		}
		if out != nil && len(f.Result) > 0 {
			if err := json.Unmarshal(f.Result, out); err != nil {
				return receipt, fmt.Errorf("%s: decode result: %w", method, err)
			}
		}
		return receipt, nil
	}
}

// notify sends a client->server notification, which expects no reply.
func (c *conn) notify(method string, params any) error {
	payload := map[string]any{"method": method}
	if params != nil {
		payload["params"] = params
	}
	return c.write(payload)
}

// closeWrite closes stdin, which is how app-server is asked to shut down
// gracefully. The read loop then ends on EOF.
func (c *conn) closeWrite() error { return c.w.Close() }
